// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxFZz_GJWHK_kGJCT0texQlb7zDcYw6b8',
    appId: '1:158862585284:web:190a11a0ff972b46868891',
    messagingSenderId: '158862585284',
    projectId: 'melodymap-d2dbd',
    authDomain: 'melodymap-d2dbd.firebaseapp.com',
    storageBucket: 'melodymap-d2dbd.appspot.com',
    measurementId: 'G-LQH4TMVNCH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_tVXNtVxFx-nsdYv-wNoPPUjmnQDMGYE',
    appId: '1:158862585284:android:51bc2e3668187119868891',
    messagingSenderId: '158862585284',
    projectId: 'melodymap-d2dbd',
    storageBucket: 'melodymap-d2dbd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPgzZ4WkPlAiQGkl0T3U5KYmzkd3swCIM',
    appId: '1:158862585284:ios:430faea17329c6f0868891',
    messagingSenderId: '158862585284',
    projectId: 'melodymap-d2dbd',
    storageBucket: 'melodymap-d2dbd.appspot.com',
    iosBundleId: 'com.example.melodymap',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPgzZ4WkPlAiQGkl0T3U5KYmzkd3swCIM',
    appId: '1:158862585284:ios:6cb4310f3555f0f4868891',
    messagingSenderId: '158862585284',
    projectId: 'melodymap-d2dbd',
    storageBucket: 'melodymap-d2dbd.appspot.com',
    iosBundleId: 'com.example.melodymap.RunnerTests',
  );
}
